buildscript {
    repositories {
        jcenter()
        mavenLocal()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenLocal()
        google()
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.6'
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
