plugins {
    id 'com.android.application'
}

android {
    namespace 'com.github.victor.mover'
    compileSdk 35
    buildToolsVersion '34.0.0'

    defaultConfig {
        applicationId "com.github.victor.mover"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode   131
        versionName   "1.2.118"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    signingConfigs {
        release {
            storeFile file(project.findProperty('RELEASE_STORE_FILE') ?: 'none')
            storePassword project.findProperty('RELEASE_STORE_PASSWORD')
            keyAlias project.findProperty('RELEASE_KEY_ALIAS')
            keyPassword project.findProperty('RELEASE_KEY_PASSWORD')
        }
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFileName = org.apache.commons.io.FilenameUtils.getExtension(android.defaultConfig.applicationId) + "-" + android.defaultConfig.versionName + "-" + variant.buildType.name + ".apk"
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation project(':android-library')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'commons-io:commons-io:2.11.0'
}
