apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    buildToolsVersion '36.0.0'
    namespace 'com.github.axet.mover'

    defaultConfig {
        applicationId "com.github.axet.mover"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode   130
        versionName   "1.2.117"
    }

    signingConfigs {
        release {
            storeFile file(project.findProperty('RELEASE_STORE_FILE') ?: 'none')
            storePassword project.findProperty('RELEASE_STORE_PASSWORD')
            keyAlias project.findProperty('RELEASE_KEY_ALIAS')
            keyPassword project.findProperty('RELEASE_KEY_PASSWORD')
        }
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = org.apache.commons.io.FilenameUtils.getExtension(variant.applicationId) + "-" + variant.versionName + "-" + variant.buildType.name + ".apk"
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.github.axet:android-library:1.37.1'
    implementation 'com.google.android.material:material:1.12.0'
}
